USE pbjproject;

CREATE TABLE Bread (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	brand VARCHAR(100) NOT NULL,
	wheatLevel INT NOT NULL,
	price DECIMAL(8,2) NOT NULL
);


CREATE TABLE Peanut_Butter (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	brand VARCHAR(100) NOT NULL,
	isCrunchy BOOLEAN NOT NULL,
	price DECIMAL(8,2) NOT NULL
);


CREATE TABLE Jelly (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	brand VARCHAR(100) NOT NULL,
	flavor VARCHAR(100) NOT NULL,
	price DECIMAL(8,2) NOT NULL
);


CREATE TABLE Pbj_Sandwich (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	customer VARCHAR(150) NOT NULL,
	bread1_id INT NOT NULL,
	pb_id INT NOT NULL,
	jelly_id INT NOT NULL,
	bread2_id INT NOT NULL,
	totalCost DECIMAL(10,2) NOT NULL,
	FOREIGN KEY (bread1_id) REFERENCES Bread(ID),
	FOREIGN KEY (pb_id) REFERENCES Peanut_Butter(ID),
	FOREIGN KEY (jelly_id) REFERENCES Jelly(ID),
	FOREIGN KEY (bread2_id) REFERENCES Bread(ID)
);